#!/usr/bin/env bash
# Script to install and configure Nginx listed in port 80
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
ufw allow  'Nginx HTTP'
chmod 777 /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
chmod 644 /var/www/html/index.nginx-debian.html
service nginx restart