#!/usr/bin/env bash
# Script to install and configure Nginx listed in port 80
apt-get -y update
apt-get -y install nginx
ufw allow  'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html