#!/usr/bin/env bash
# Script to install and configure Nginx listed in port 80 with a redirection
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
chmod 777 /var/www/html/index.nginx-debian.html
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
chmod 644 /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a \\\nrewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
touch /var/www/html/custom_404.html
chmod 777 /var/www/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
chmod 644 /var/www/html/custom_404.html
sed -i "/server_name _;/ a \\\nerror_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sed -i "/server_name _;/ a \\\nadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart