#!/bin/env bash
# Script to install and configure HAProxy 1.6.
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy=1.6.*
echo -e "frontend http\n\tbind *:80\n\tdefault_backend 01_backend\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend 01_backend\n\tbalance roundrobin\n\tserver 2309-web-01 35.196.217.143:80 check\n\tserver 2309-web-02 3.85.208.251:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart