#!/usr/bin/env bash
# This script check if a file exist.

file=holbertonschool

if test -e "$file"; then
	echo "$file file exists"
	if test -s "$file"; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	if test -f "$file"; then
		echo "$file is a regular file"
	fi
else
	echo "$file file not exist"
fi